# Generated by Django 3.2.8 on 2023-03-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
